# Generated by Django 4.2.2 on 2023-06-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportistas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50, null=True)),
                ('torneo', models.CharField(max_length=50, null=True)),
                ('lugar', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('encargado', models.CharField(max_length=50, null=True)),
                ('direccion', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
