# Generated by Django 4.2.2 on 2023-06-23 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deportistas', '0002_competencia_sede'),
    ]

    operations = [
        migrations.AddField(
            model_name='deportista',
            name='competencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='deportistas.competencia'),
        ),
        migrations.AddField(
            model_name='deportista',
            name='sede',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='deportistas.sede'),
        ),
    ]
